apiVersion: v1
kind: Pod
metadata:
  name: empty-dir-example-pod
  namespace: default
  labels:
    app: emptyDir  
  annotations:
    description: "empty dir example pod"
    owner: "aldair"
spec:
  containers:
    - name: app-input
      image: busybox:latest
      ports:
        - containerPort: 8080
      env:
        - name: VARIABLE
          value: "abc123"
      resources:
        limits:
          cpu: "1000m"
          memory: "256Mi"
        requests:
          cpu: "500m"
          memory: "128Mi"
      command: ["/bin/sh", "-c"]
      args: ["date > /app/date.txt && sleep 3600"]
      volumeMounts:
        - name: data
          mountPath: /app

    - name: app-output
      image: busybox:latest
      ports:
        - containerPort: 80
        - containerPort: 443
      env:
        - name: VARIABLE
          value: "123ABC"
      resources:
        limits:
          cpu: "1000m"
          memory: "256Mi"
        requests:
          cpu: "500m"
          memory: "128Mi"
      command: ["/bin/sh", "-c"]
      args: ["sleep 3600"]
      volumeMounts:
        - name: data
          mountPath: /output

  volumes:
    - name: data
      emptyDir: {}